ui: mocha-bdd
tunnel:
  type: ngrok
  authtoken: LsVZFxFqgxA4h7ibWV9V_iuA9afbQwaSnGqH9dApL
browsers:
  - name: chrome
    version: latest
  - name: safari
    version: 9
  - name: firefox
    version: latest
  - name: ie
    version: 10..latest
browserify:
  - transform:
      name: babelify
  - options:
      extensions:
        - .jsx
